@Restaurant.API_HostAddress = https://localhost:7049

@host = https://localhost
@port = 7049
@token = CfDJ8BWwd6bU_aJOqFqnjdD6hnoF4xVAUhbhWP-J2aPAJuCignNYNBg72KuhkAyA-goehlVa9e4Hvr2F98voHXbhcyQu8NR7tsqd3DXJwSf1_Y1phIaY4O0JweWvqRxRTTPlvwlNwcVA2zmfZCfhcwfTS7SSEcYP85wzRkxLDICnaOFTOzq1KEFlWFcedqTPiuRTyXrFEDifLL2QM_Gm2J2s5kLQxpDzBalIlHIlWv7eUgEBuVN_9A9BjEDs8DxaUlJPoeJqdfibCI9NYwH5rE363qvx3jcyrS0VIKfoD_47cFz-MXlhvtFvkx70kfkVoTLfQN8Ux1_J6HoAWcYX-R2HTwvUIIw04bOfKgNKfWMr8fui1QPPDCH0rh24l-SA8uTS1zFp9cUg2GvY56PJr_Gx52qfvm-Q-HRegGdLgbVSdHWlMNmGem5l2hSPEDCSk4hhueEgAAZxMb8EAPzC48t1bqpvy6DxCiP-UIE-n_dvCIqRzYJ3Y84Ycj1J_n8qLzQjKuIhIQLpL8EmGTUhEgY7Cqv_i_-kSrbS4TLCPqkMM1C_YxIkET9AtkB-chatM72Sm_l4eMp-9EUXb2K3xYLwP_DQ-UYtNrllh8CqwIjD7zXyB5i95cjL3JtXW-8s6B4SWBaBMJVitxkQxlVsXgMcmMEtBsjF6B948E10dqfCXIX_6imaGJ-0yQUi-OLRiKn93tJCZ2hestoSfxW_SCTpTQcWOs6VzQiDFZZYecED3zMGJkhTENTwpRCbnT1ddxNKgZg_3jgYGqjEZW2hufcd8cX6iDoFL3T6XCqn8P_fiX60
@Restaurants.API_HostAddress = {{host}}:{{port}}


GET {{Restaurant.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}


###



GET {{Restaurant.API_HostAddress}}/api/restaurants/12


###

POST {{Restaurant.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json
{
    "Name": "Lolll",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###

DELETE {{Restaurant.API_HostAddress}}/api/restaurants/9



###
PATCH {{Restaurant.API_HostAddress}}/api/restaurants/10
Content-Type: application/json

{
  "Name": "Boba",
  "Description": "d",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/10/dishes
Content-Type: application/json
{

}
###

GET {{Restaurants.API_HostAddress}}/api/restaurant/10/dishes/3


###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "owner@gmail.com",
  "password": "Owner!12"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@gmail.com",
  "password": "Owner!12"
}
